### ISSUE TITLE
Can't load agent in other namespace. 

### ISSUE THREAD

**Issue by skrbug** [apangin/jattach#40]
Run two containers.  
One was privileged container (`docker run  -it --privileged=true --pid=host openjdk-8-jdk  bash`) 
I copy jattach into privileged container. 

I have copied the file(agent.jar) to another container(spring project) before executing the command

`jattach  28509 load instrument false "/agent.jar"`  

```
root@a83b8d5684cf:/dosec/memshell_detect# jattach  28509 load instrument false "/agent.jar"
Connected to remote JVM
Response code = 0
return code: 102
```

pid = `28509` is another container which run springboot demo. I get this pid by `docker inspect xxx | grep -i "pid"`  

container  log 
The result is the same, whether the container jdk is 8 or 11
```
2021-05-16 06:52:43.266  INFO 1 --- [           main] com.example.demo.DemoApplication         : Starting DemoApplication v0.0.1-SNAPSHOT using Java 11.0.11 on 1047004b4806 with PID 1 (/app.jar started by root in /)
2021-05-16 06:52:43.268  INFO 1 --- [           main] com.example.demo.DemoApplication         : No active profile set, falling back to default profiles: default
2021-05-16 06:52:43.884  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
2021-05-16 06:52:43.893  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2021-05-16 06:52:43.893  INFO 1 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.45]
2021-05-16 06:52:43.929  INFO 1 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2021-05-16 06:52:43.929  INFO 1 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 623 ms
2021-05-16 06:52:44.056  INFO 1 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2021-05-16 06:52:44.183  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''
2021-05-16 06:52:44.191  INFO 1 --- [           main] com.example.demo.DemoApplication         : Started DemoApplication in 1.218 seconds (JVM running for 1.618)
Exception in thread "Attach Listener" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallAgentmain(InstrumentationImpl.java:535)
Caused by: java.lang.NullPointerException
        at cn.dosec.copagent.Agent.catchThief(Agent.java:79)
        at cn.dosec.copagent.Agent.agentmain(Agent.java:22)
        ... 6 more
Agent failed to start!
```

Is it possible load agent by this way?

**Comment by apangin** [comment]
`jattach` did its job - the agent has been successfully loaded into the target process.

As you can see in the stack trace, it's the agent code being executed:
```
Caused by: java.lang.NullPointerException
        at cn.dosec.copagent.Agent.catchThief(Agent.java:79)
        at cn.dosec.copagent.Agent.agentmain(Agent.java:22)
```

Looks like a problem in the agent code.

**Comment by skrbug** [comment]
Thanks,I forgot to pass in the parameters。
